PF2/PF2/Models/Node.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.Node1 = new HashSet<Node>();
            this.Question = new HashSet<Question>();
            this.Quiz = new HashSet<Quiz>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<Node> Node1 { get; set; }
        public virtual Node Node2 { get; set; }
        public virtual ICollection<Question> Question { get; set; }
        public virtual ICollection<Quiz> Quiz { get; set; }
    }
}

PF2/PF2/Controllers/NodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PF2.Models;
using PF2.Services;

namespace PF2.Controllers
{
    public class NodesController : Controller
    {
        private DefaultConnectionEntities db = new DefaultConnectionEntities();

        // GET: Nodes
        public ActionResult List()
        {
            var node = db.Node.Include(n => n.Node2);
            return View(node.ToList());
        }

        [HttpGet]
        public ActionResult ListTrees()
        {
            using (var db = new DefaultConnectionEntities())
            {
                List<Node> resultado = (from c in db.Node
                                        where c.ParentId == null
                                        select c).ToList();
                return View(resultado);
            }
        }


        // GET: Nodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Node node = db.Node.Find(id);
            if (node == null)
            {
                return HttpNotFound();
            }
            return View(node);
        }

        // GET: Nodes/Create
        public ActionResult Create(int? parentId)
        {
            ViewBag.ParentId = parentId;
            return View();
        }

        // POST: Nodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NodeID,Name,Description,ParentID")] Node node)
        {
            if (ModelState.IsValid)
            {
                db.Node.Add(node);
                db.SaveChanges();
                return RedirectToAction("VisualizeTree", new { id = GetTreeRootFromNode(node.Id).Id });
            }

            //ViewBag.ParentId = new SelectList(db.Node, "NodeID", "Name", node.ParentID);
            return View(node);
        }

        // GET: Nodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Node node = db.Node.Find(id);
            if (node == null)
            {
                return HttpNotFound();
            }
            if (node.ParentId != null)
            {
                ViewBag.ParentId = new SelectList(db.Node, "Id", "Name", node.ParentId);
            }
            return View(node);
        }

        // POST: Nodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Node node)
        {
            if (ModelState.IsValid)
            {
                db.Entry(node).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("VisualizeTree", new { id = GetTreeRootFromNode(node.Id).Id });
            }
            ViewBag.ParentId = new SelectList(db.Node, "NodeID", "Name", node.ParentId);
            return View(node);
        }

        // GET: Nodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Node node = db.Node.Find(id);
            if (node == null)
            {
                return HttpNotFound();
            }
            return View(node);
        }

        // POST: Nodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Node node = db.Node.Find(id);
            bool isRoot=(node.ParentId == null);

            //Define para o controlador redirecionar para o controlador VisualizeTree passando o id da raiz da árvore
            ActionResult returnValue = RedirectToAction("VisualizeTree", new { id = GetTreeRootFromNode(node.Id).Id });
          
            //Se o node sendo deletado for o node raiz, redireciona para a lista de arvores
            if (isRoot)
            {
                returnValue = RedirectToAction("ListTrees");
            }

            NodeService.DeleteNode(db,id);
            /**
            db.Node.Remove(node);
            db.SaveChanges();
            **/
            return returnValue;
        }

        [HttpGet]
        public ActionResult VisualizeFullTree(int id)
        {

            return RedirectToAction("VisualizeTree", new { id = GetTreeRootFromNode(id).Id });
        }

        [HttpGet]
        public ActionResult VisualizeTree(int id)
        {
            return View(GetNodeSons(id));
        }

        public Tree GetNodeSons(int id)
        {
            using (var db = new DefaultConnectionEntities())
            {
                Tree tree = new Tree();
                Node node = db.Node.Find(id);
                tree.node = node;

                List<Node> resultado = (from c in db.Node
                                        where c.ParentId == id
                                        select c).ToList();

                foreach (var n in resultado)
                {
                    tree.sons.Add(GetNodeSons(n.Id));
                }

                return tree;
            }
        }

        private Node GetTreeRootFromNode(int nodeID)
        {

            Node node = db.Node.Find(nodeID);
            while (node.ParentId != null)
            {
                node = db.Node.Find(node.ParentId);
            }

            return node;
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PF2/PF2/Views/Nodes/Create.cshtml
@model PF2.Models.Node



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Node</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
           @Html.HiddenFor(model => model.ParentId, (int?)ViewBag.ParentId)
           <p> @ViewBag.ParentId  <<<</p>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
      
        @if ((int?)ViewBag.ParentId != null) 
        { 
            @Html.ActionLink("Full Tree", "VisualizeFullTree", new { id = (int)ViewBag.ParentId })
        }
        else
        {
            @Html.ActionLink("List Trees", "ListTrees")
        }
    </div>
</body>
</html>

PF2/PF2/Views/Nodes/Delete.cshtml
@model PF2.Models.Node


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Node</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Node2.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Node2.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                
                @if (Model.ParentId != null)
                {
                    @Html.ActionLink("Full Tree", "VisualizeFullTree", new { id = Model.Id })
                }
                else
                {
                    @Html.ActionLink("List Trees", "ListTrees")
                }

            </div>
        }
    </div>
</body>
</html>

PF2/PF2/Views/Nodes/Details.cshtml
@model PF2.Models.Node


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Node</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Node2.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Node2.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @if (Model.ParentId != null)
        {
            @Html.ActionLink("Full Tree", "VisualizeFullTree", new { id = Model.Id })
        }
        else
        {
            @Html.ActionLink("List Trees", "ListTrees")
        }
    </p>
</body>
</html>

PF2/PF2/Views/Nodes/Edit.cshtml
@model PF2.Models.Node



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Node</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            @if (Model.ParentId != null)
            {
            <div class="form-group">
                @Html.LabelFor(model => model.ParentId, "ParentId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ParentId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                </div>
            </div>
            }
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @if (Model.ParentId != null)
        {
            @Html.ActionLink("Full Tree", "VisualizeFullTree", new { id = Model.Id })
        }
        else
        {
            @Html.ActionLink("List Trees", "ListTrees")
        }
    </div>
</body>
</html>

PF2/PF2/Views/Nodes/List.cshtml
@model IEnumerable<PF2.Models.Node>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Node2.Name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Node2.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

PF2/PF2/Views/Nodes/ListTrees.cshtml
@model IEnumerable<PF2.Models.Node>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Node2.Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                    @Html.ActionLink("Visualize", "VisualizeTree", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</body>
</html>

PF2/PF2/Views/Nodes/VisualizeTree.cshtml
@model PF2.Models.Tree


<!DOCTYPE html>

<html>
<head>
    <link href="~/Contents/Styles_tree.css" rel="stylesheet" type="text/css" />
    <meta name="viewport" content="width=device-width" />
    <title>VisualizeTree</title>
</head>
<body>
    <div class="tree">
        <ul>
            <li>
                <div class="node">
                    <p>@Html.DisplayFor(model => model.node.Name)</p>
                    <a href="@Url.Action("Create", "Nodes", new { parentId = Model.node.Id })"> <img src="~/Contents/Images/leaf_plus.png"> </a>
                    @if(Model.sons.Count==0){
                        <a href="@Url.Action("Delete", "Nodes", new { id = Model.node.Id })"> <img src="~/Contents/Images/leaf_minus.png"> </a>
                    }
                    <a href="@Url.Action("Edit", "Nodes",new { id = Model.node.Id })"> <img src="~/Contents/Images/leaf_pencil.png"> </a>
                    <a href="@Url.Action("Details", "Nodes", new { id = Model.node.Id })"> <img src="~/Contents/Images/leaf_lupe.png"> </a>

                </div>  
                @if (Model.sons.Count != 0)
                {
                    <ul>
                        @foreach (var t in Model.sons)
                        {
                            @Html.Partial("_PartialTreeView", t);
                        }
                    </ul>
                }
                else 
                {
                <div class="NodeQuestionLink">
                    <a href="@Url.Action("ListNodeQuestions", "Questions", new { nodeId = Model.node.Id })">Questions</a>
                </div>
                }

            </li>
        </ul>
     </div>




</body>
</html>

PF2/PF2/Views/Nodes/_PartialTreeView.cshtml
@model PF2.Models.Tree

@{
    Layout = null;
}

<!DOCTYPE html>
        <li>
            <div class="node">
                <p>@Html.DisplayFor(model => model.node.Name)</p>
                <a href="@Url.Action("Create", "Nodes", new { parentId = Model.node.Id })"> <img src="~/Contents/Images/leaf_plus.png"> </a>
                @if(Model.sons.Count==0){
                    <a href="@Url.Action("Delete", "Nodes", new { id = Model.node.Id })"> <img src="~/Contents/Images/leaf_minus.png"> </a>
                }
                <a href="@Url.Action("Edit", "Nodes",new { id = Model.node.Id })"> <img src="~/Contents/Images/leaf_pencil.png"> </a>
                
                <a href="@Url.Action("Details", "Nodes", new { id = Model.node.Id })"> <img src="~/Contents/Images/leaf_lupe.png"> </a>

            </div>
            @if(Model.sons.Count!=0){

                <ul>
                    @foreach (var t in Model.sons)
                    {
                        @Html.Partial("_PartialTreeView", t);
                    }
                </ul>
            }
            else
            {
                <div class="NodeQuestionLink">
                    <a href="@Url.Action("ListNodeQuestions", "Questions", new { nodeId = Model.node.Id })">Questions</a>
                </div>
            }
        </li>